./heritability_estimation_GREML_train_set_only.sh PE-P-18:1-22:6-_-a-
./heritability_estimation_GREML_train_set_only.sh PC-16:0_18:0-
./heritability_estimation_GREML_train_set_only.sh CE-20:2-
./heritability_estimation_GREML_train_set_only.sh SM-43:1-
./heritability_estimation_GREML_train_set_only.sh SM-43:2-_-b-
./heritability_estimation_GREML_train_set_only.sh PE-P-16:0-22:4-
./heritability_estimation_GREML_train_set_only.sh AC-18:1-
./heritability_estimation_GREML_train_set_only.sh SM-d18:1-23:0--SM-d17:1-24:0-
./heritability_estimation_GREML_train_set_only.sh PC-31:0-_-b-
./heritability_estimation_GREML_train_set_only.sh HexCer-d16:1-20:0-
./heritability_estimation_GREML_train_set_only.sh TG-50:3-_[NL-14:0]
./heritability_estimation_GREML_train_set_only.sh CE-24:5-
./heritability_estimation_GREML_train_set_only.sh TG-53:2-_[NL-17:1]
./heritability_estimation_GREML_train_set_only.sh LPC-P-17:0-_-b-
./heritability_estimation_GREML_train_set_only.sh AC-24:1-_-b-
./heritability_estimation_GREML_train_set_only.sh Cer-d18:1-18:0-
./heritability_estimation_GREML_train_set_only.sh TG-54:4-_[NL-20:3]
./heritability_estimation_GREML_train_set_only.sh LPC-20:4-_[sn2]
./heritability_estimation_GREML_train_set_only.sh PE-O-16:0-18:2-
./heritability_estimation_GREML_train_set_only.sh PE-P-18:0-22:5-_-n6-
./heritability_estimation_GREML_train_set_only.sh PC-18:1_18:2-
./heritability_estimation_GREML_train_set_only.sh dhCer-d18:0-16:0-
./heritability_estimation_GREML_train_set_only.sh CE-18:2-_[+OH]
./heritability_estimation_GREML_train_set_only.sh PC-P-18:1-22:6-
./heritability_estimation_GREML_train_set_only.sh FA-20:2-
./heritability_estimation_GREML_train_set_only.sh PC-44:5-
./heritability_estimation_GREML_train_set_only.sh SM-40:3-_-b-
./heritability_estimation_GREML_train_set_only.sh LPE-P-20:0-
./heritability_estimation_GREML_train_set_only.sh PE-18:1_22:6-_-a-
./heritability_estimation_GREML_train_set_only.sh PE-O-18:0-20:4-
./heritability_estimation_GREML_train_set_only.sh CE-24:4-
./heritability_estimation_GREML_train_set_only.sh Cer-m18:1-23:0-
./heritability_estimation_GREML_train_set_only.sh GM3-d18:1-24:0-
./heritability_estimation_GREML_train_set_only.sh TG-54:6-_[NL-18:3]
./heritability_estimation_GREML_train_set_only.sh PE-17:0_18:2-
./heritability_estimation_GREML_train_set_only.sh PC-18:0_22:4-
./heritability_estimation_GREML_train_set_only.sh PC-15:0_22:6-
./heritability_estimation_GREML_train_set_only.sh PE-16:0_20:5-
./heritability_estimation_GREML_train_set_only.sh LPE-20:4-_[sn2]
./heritability_estimation_GREML_train_set_only.sh SM-41:1-_-a-
./heritability_estimation_GREML_train_set_only.sh DG-18:1_18:2-
./heritability_estimation_GREML_train_set_only.sh LPC-26:0-_[sn1]
./heritability_estimation_GREML_train_set_only.sh SHexCer-d18:1-24:1-OH--
./heritability_estimation_GREML_train_set_only.sh LPE-P-18:1-
./heritability_estimation_GREML_train_set_only.sh LPC-O-20:1-
./heritability_estimation_GREML_train_set_only.sh PC-P-17:0-20:4-_-a-
./heritability_estimation_GREML_train_set_only.sh Hex2Cer-d18:2-16:0-
./heritability_estimation_GREML_train_set_only.sh SM-34:3-
./heritability_estimation_GREML_train_set_only.sh CE-20:5-
./heritability_estimation_GREML_train_set_only.sh PE-O-18:0-22:6-
./heritability_estimation_GREML_train_set_only.sh LPE-17:0-
./heritability_estimation_GREML_train_set_only.sh PC-42:3-_-b-
./heritability_estimation_GREML_train_set_only.sh PC-42:5-_-a-
./heritability_estimation_GREML_train_set_only.sh LPC-16:1-_[sn1]
./heritability_estimation_GREML_train_set_only.sh PC-18:0_20:4-
./heritability_estimation_GREML_train_set_only.sh PC-38:5-_-b-
./heritability_estimation_GREML_train_set_only.sh TG-54:3-_[SIM]
./heritability_estimation_GREML_train_set_only.sh AC-18:0--OH
./heritability_estimation_GREML_train_set_only.sh methyl-CE-18:1-
./heritability_estimation_GREML_train_set_only.sh PC-16:0_18:3-_-a-
./heritability_estimation_GREML_train_set_only.sh LPI-18:0-
./heritability_estimation_GREML_train_set_only.sh AC-20:5-
./heritability_estimation_GREML_train_set_only.sh HexCer-d18:1-20:0-
./heritability_estimation_GREML_train_set_only.sh LPC-P-18:1-
./heritability_estimation_GREML_train_set_only.sh TG-48:0-_[SIM]
./heritability_estimation_GREML_train_set_only.sh PE-18:0_22:5-_-n3-
./heritability_estimation_GREML_train_set_only.sh PC-38:7-_-c-
./heritability_estimation_GREML_train_set_only.sh PA-36:3-
./heritability_estimation_GREML_train_set_only.sh SM-42:3-
./heritability_estimation_GREML_train_set_only.sh TG-58:10-_[SIM]
./heritability_estimation_GREML_train_set_only.sh SM-40:3-_-a-
./heritability_estimation_GREML_train_set_only.sh PC-18:0_20:3-
./heritability_estimation_GREML_train_set_only.sh PE-16:0_16:0-
./heritability_estimation_GREML_train_set_only.sh LPI-18:1-_[sn1]
./heritability_estimation_GREML_train_set_only.sh TG-50:3-_[NL-18:2]
./heritability_estimation_GREML_train_set_only.sh TG-O-54:2-_[SIM]
./heritability_estimation_GREML_train_set_only.sh GM3-d18:2-24:1-
./heritability_estimation_GREML_train_set_only.sh PC-42:9-_-b-
./heritability_estimation_GREML_train_set_only.sh PE-16:0_20:3-
./heritability_estimation_GREML_train_set_only.sh FA-20:5-
./heritability_estimation_GREML_train_set_only.sh COH
./heritability_estimation_GREML_train_set_only.sh PC-16:0_18:2-
./heritability_estimation_GREML_train_set_only.sh SHexCer-d18:1-16:0-
./heritability_estimation_GREML_train_set_only.sh Cer-d20:1-24:1-
./heritability_estimation_GREML_train_set_only.sh AC-20:3-_-b-
./heritability_estimation_GREML_train_set_only.sh LPC-22:6-_[sn1]
./heritability_estimation_GREML_train_set_only.sh AC-16:1--OH
./heritability_estimation_GREML_train_set_only.sh LPC-18:2-_[sn2]
./heritability_estimation_GREML_train_set_only.sh Cer-m18:1-22:0-
./heritability_estimation_GREML_train_set_only.sh CE-20:0-
./heritability_estimation_GREML_train_set_only.sh PE-O-18:0-22:5-
./heritability_estimation_GREML_train_set_only.sh PC-O-36:5-
./heritability_estimation_GREML_train_set_only.sh AC-13:0-
./heritability_estimation_GREML_train_set_only.sh PC-O-40:5-
./heritability_estimation_GREML_train_set_only.sh TG-56:9-_[NL-22:6]
./heritability_estimation_GREML_train_set_only.sh Cer-m18:0-20:0-
./heritability_estimation_GREML_train_set_only.sh Cer-d18:2-20:0-
./heritability_estimation_GREML_train_set_only.sh LPC-19:1-_-a-
./heritability_estimation_GREML_train_set_only.sh PC-38:4-_-b-
./heritability_estimation_GREML_train_set_only.sh LPC-O-20:0-
./heritability_estimation_GREML_train_set_only.sh CE-24:0-
./heritability_estimation_GREML_train_set_only.sh AC-14:1--OH
./heritability_estimation_GREML_train_set_only.sh SM-41:0-
./heritability_estimation_GREML_train_set_only.sh TG-48:3-_[NL-16:1]
./heritability_estimation_GREML_train_set_only.sh LPC-22:5-_[sn1]_-n3--LPC-22:5-_[sn2]_-n6-
./heritability_estimation_GREML_train_set_only.sh TG-56:8-_[NL-22:6]
./heritability_estimation_GREML_train_set_only.sh LPE-16:0-_[sn2]
./heritability_estimation_GREML_train_set_only.sh HexCer-d18:2-22:0-
./heritability_estimation_GREML_train_set_only.sh PC-O-18:0-18:2-
./heritability_estimation_GREML_train_set_only.sh LPC-20:4-_[sn1]
./heritability_estimation_GREML_train_set_only.sh PS-38:4-
./heritability_estimation_GREML_train_set_only.sh PE-P-15:0-22:6-_-a-
./heritability_estimation_GREML_train_set_only.sh PE-18:1_18:1-
./heritability_estimation_GREML_train_set_only.sh PC-P-16:0-16:0-
./heritability_estimation_GREML_train_set_only.sh Cer-d20:1-23:0-
./heritability_estimation_GREML_train_set_only.sh CE-17:1-
./heritability_estimation_GREML_train_set_only.sh PC-O-18:0-20:4-
./heritability_estimation_GREML_train_set_only.sh TG-48:0-_[NL-18:0]
./heritability_estimation_GREML_train_set_only.sh PC-O-16:0-20:3-
./heritability_estimation_GREML_train_set_only.sh Hex2Cer-d18:1-24:0-
./heritability_estimation_GREML_train_set_only.sh LPC-24:0-_[sn2]
./heritability_estimation_GREML_train_set_only.sh TG-O-50:1-_[NL-15:0]
./heritability_estimation_GREML_train_set_only.sh PC-P-18:0-18:2-
./heritability_estimation_GREML_train_set_only.sh PC-O-44:7-
./heritability_estimation_GREML_train_set_only.sh TG-54:2-_[SIM]
./heritability_estimation_GREML_train_set_only.sh Cer-m18:0-24:0-
./heritability_estimation_GREML_train_set_only.sh PE-38:5-_-a-
./heritability_estimation_GREML_train_set_only.sh SM-d18:2-17:0-
./heritability_estimation_GREML_train_set_only.sh AC-14:0-
./heritability_estimation_GREML_train_set_only.sh SHexCer-d18:1-24:0-OH--
./heritability_estimation_GREML_train_set_only.sh LPE-P-18:0-
./heritability_estimation_GREML_train_set_only.sh PE-P-17:0-20:4-_-b-
./heritability_estimation_GREML_train_set_only.sh PC-O-32:2-
./heritability_estimation_GREML_train_set_only.sh PC-14:0_16:0-
./heritability_estimation_GREML_train_set_only.sh PE-P-16:0-20:3-_-a-
./heritability_estimation_GREML_train_set_only.sh LPC-22:4-_[sn2]
./heritability_estimation_GREML_train_set_only.sh Hex3Cer-d18:1-16:0-
./heritability_estimation_GREML_train_set_only.sh PC-P-20:0-20:4-
./heritability_estimation_GREML_train_set_only.sh SM-43:2-_-c-
./heritability_estimation_GREML_train_set_only.sh PE-P-18:0-20:3-_-a-
./heritability_estimation_GREML_train_set_only.sh PE-18:0_22:5-_-n6-
./heritability_estimation_GREML_train_set_only.sh SM-d18:2-18:0-
./heritability_estimation_GREML_train_set_only.sh S1P-d16:1-
./heritability_estimation_GREML_train_set_only.sh Cer-d19:1-18:0-
./heritability_estimation_GREML_train_set_only.sh PC-34:2-_[+OH]
./heritability_estimation_GREML_train_set_only.sh PC-40:7-_-a-
./heritability_estimation_GREML_train_set_only.sh LPC-O-22:0-
./heritability_estimation_GREML_train_set_only.sh PI-18:0_22:6-
./heritability_estimation_GREML_train_set_only.sh Cer-d19:1-24:1-
./heritability_estimation_GREML_train_set_only.sh methyl-CE-18:0-
./heritability_estimation_GREML_train_set_only.sh dimethyl-CE-20:4-
./heritability_estimation_GREML_train_set_only.sh PC-16:0_22:6-
./heritability_estimation_GREML_train_set_only.sh CE-20:3-
./heritability_estimation_GREML_train_set_only.sh Cer-m18:1-24:0-
./heritability_estimation_GREML_train_set_only.sh PC-O-32:1-
./heritability_estimation_GREML_train_set_only.sh TG-58:9-_[NL-22:6]
./heritability_estimation_GREML_train_set_only.sh DG-16:0_18:1-
./heritability_estimation_GREML_train_set_only.sh PC-O-40:7-
./heritability_estimation_GREML_train_set_only.sh Cer-d18:1-24:0-
./heritability_estimation_GREML_train_set_only.sh HexCer-d18:2-18:0-
./heritability_estimation_GREML_train_set_only.sh PC-P-16:0-20:4-
./heritability_estimation_GREML_train_set_only.sh TG-54:6-_[NL-20:4]
./heritability_estimation_GREML_train_set_only.sh PC-18:0_22:5-_-n6-
./heritability_estimation_GREML_train_set_only.sh dimethyl-CE-22:6-
./heritability_estimation_GREML_train_set_only.sh FA-17:0-
./heritability_estimation_GREML_train_set_only.sh PC-33:2-
./heritability_estimation_GREML_train_set_only.sh PC-P-16:0-18:0-
./heritability_estimation_GREML_train_set_only.sh PC-O-38:5-
./heritability_estimation_GREML_train_set_only.sh DG-17:1_18:1-
./heritability_estimation_GREML_train_set_only.sh PC-44:4-_-a-
./heritability_estimation_GREML_train_set_only.sh dhCer-d18:0-20:0-
./heritability_estimation_GREML_train_set_only.sh SM-d18:1-14:0--SM-d16:1-16:0-
./heritability_estimation_GREML_train_set_only.sh TG-48:3-_[NL-14:0]
./heritability_estimation_GREML_train_set_only.sh PE-O-16:0-22:4-
./heritability_estimation_GREML_train_set_only.sh Cer-d18:2-18:0-
./heritability_estimation_GREML_train_set_only.sh PC-O-42:5-_-c-
./heritability_estimation_GREML_train_set_only.sh TG-50:1-_[NL-18:1]
./heritability_estimation_GREML_train_set_only.sh PE-16:1_20:4-
./heritability_estimation_GREML_train_set_only.sh TG-51:2-_[NL-15:0]
./heritability_estimation_GREML_train_set_only.sh AC-24:1-_-a-
./heritability_estimation_GREML_train_set_only.sh FA-18:3-
./heritability_estimation_GREML_train_set_only.sh TG-54:7-_[NL-20:5]
./heritability_estimation_GREML_train_set_only.sh SHexCer-d18:1-24:1-
./heritability_estimation_GREML_train_set_only.sh PC-40:8-
./heritability_estimation_GREML_train_set_only.sh PI-20:0_20:4-
./heritability_estimation_GREML_train_set_only.sh TG-48:1-_[NL-18:1]
./heritability_estimation_GREML_train_set_only.sh CE-20:1-
./heritability_estimation_GREML_train_set_only.sh LPC-24:0-_[sn1]
./heritability_estimation_GREML_train_set_only.sh PC-16:0_18:1-
./heritability_estimation_GREML_train_set_only.sh PE-P-18:0-22:4-
./heritability_estimation_GREML_train_set_only.sh SM-38:3-_-b-
./heritability_estimation_GREML_train_set_only.sh Cer-m18:1-18:0-
./heritability_estimation_GREML_train_set_only.sh Cer-d16:1-22:0-
./heritability_estimation_GREML_train_set_only.sh PE-P-18:0-18:3-
./heritability_estimation_GREML_train_set_only.sh Cer-d18:1-23:0-
./heritability_estimation_GREML_train_set_only.sh DG-18:1_22:5-
./heritability_estimation_GREML_train_set_only.sh PC-P-16:0-20:5-
./heritability_estimation_GREML_train_set_only.sh LPC-20:1-_[sn2]
./heritability_estimation_GREML_train_set_only.sh PE-16:0_18:2-
./heritability_estimation_GREML_train_set_only.sh methyl-CE-18:2-
./heritability_estimation_GREML_train_set_only.sh PC-18:2_20:5-
./heritability_estimation_GREML_train_set_only.sh CE-15:0-
./heritability_estimation_GREML_train_set_only.sh TG-54:4-_[NL-18:2]
./heritability_estimation_GREML_train_set_only.sh PI-16:0_20:4-
./heritability_estimation_GREML_train_set_only.sh PE-15-MHDA_22:6-
./heritability_estimation_GREML_train_set_only.sh SM-d18:1-22:0--SM-d16:1-24:0-
./heritability_estimation_GREML_train_set_only.sh Hex2Cer-d16:1-24:1-
./heritability_estimation_GREML_train_set_only.sh DG-18:1_22:6-
./heritability_estimation_GREML_train_set_only.sh LPC-17:1-_[sn1]_-a-_-_LPC-17:1-_[sn2]_-b-
./heritability_estimation_GREML_train_set_only.sh TG-54:3-_[NL-18:1]
./heritability_estimation_GREML_train_set_only.sh LPC-15:0-_[sn2]
./heritability_estimation_GREML_train_set_only.sh SM-d18:2-22:0-
./heritability_estimation_GREML_train_set_only.sh FA-18:1-
./heritability_estimation_GREML_train_set_only.sh LPC-15-MHDA-_[sn1]_[104_sn1]
./heritability_estimation_GREML_train_set_only.sh PI-34:0-
./heritability_estimation_GREML_train_set_only.sh PC-O-44:6-_-b-
./heritability_estimation_GREML_train_set_only.sh DG-18:1_20:4-
./heritability_estimation_GREML_train_set_only.sh PE-P-18:1-20:4-_-b-
./heritability_estimation_GREML_train_set_only.sh SM-d18:1-18:0--SM-d16:1-20:0-
./heritability_estimation_GREML_train_set_only.sh PC-20:0_20:4-
./heritability_estimation_GREML_train_set_only.sh PE-P-18:1-20:4-_-a-
./heritability_estimation_GREML_train_set_only.sh TG-51:1-_[NL-17:0]
./heritability_estimation_GREML_train_set_only.sh PS-38:5-
./heritability_estimation_GREML_train_set_only.sh TG-54:0-_[SIM]
./heritability_estimation_GREML_train_set_only.sh Cer-d19:1-26:0-
./heritability_estimation_GREML_train_set_only.sh LPC-26:0-_[sn2]
./heritability_estimation_GREML_train_set_only.sh PC-42:2-_-a-
./heritability_estimation_GREML_train_set_only.sh DG-16:0_22:5-
./heritability_estimation_GREML_train_set_only.sh PC-18:0_18:2-
./heritability_estimation_GREML_train_set_only.sh TG-51:2-_[SIM]
./heritability_estimation_GREML_train_set_only.sh PE-P-19:0-20:4-_-b-
./heritability_estimation_GREML_train_set_only.sh LPC-18:3-_-a-_[sn1]_[104_sn1]
./heritability_estimation_GREML_train_set_only.sh PE-P-16:0-18:2-
./heritability_estimation_GREML_train_set_only.sh PC-O-16:0-16:0-
./heritability_estimation_GREML_train_set_only.sh LPC-17:0-_[sn1]
./heritability_estimation_GREML_train_set_only.sh Hex2Cer-d18:1-16:0-
./heritability_estimation_GREML_train_set_only.sh PC-O-34:2-
./heritability_estimation_GREML_train_set_only.sh PC-O-36:0-
./heritability_estimation_GREML_train_set_only.sh AC-14:2-
./heritability_estimation_GREML_train_set_only.sh DG-16:0_16:0-
./heritability_estimation_GREML_train_set_only.sh PE-O-34:1-
./heritability_estimation_GREML_train_set_only.sh TG-54:7-_[NL-22:6]
./heritability_estimation_GREML_train_set_only.sh PE-P-18:1-22:5-_-a-
./heritability_estimation_GREML_train_set_only.sh SM-d18:2-14:0-
./heritability_estimation_GREML_train_set_only.sh PE-38:5-_-b-
./heritability_estimation_GREML_train_set_only.sh TG-50:1-_[NL-16:0]
./heritability_estimation_GREML_train_set_only.sh PA-36:2-
./heritability_estimation_GREML_train_set_only.sh DG-18:1_18:3-
./heritability_estimation_GREML_train_set_only.sh SM-d18:2-23:0-
./heritability_estimation_GREML_train_set_only.sh LPC-20:4-_[+OH]
./heritability_estimation_GREML_train_set_only.sh DG-14:0_18:2-
./heritability_estimation_GREML_train_set_only.sh PC-39:5-_-b-
./heritability_estimation_GREML_train_set_only.sh Cer-d18:1-22:0-
./heritability_estimation_GREML_train_set_only.sh LPI-18:1-_[sn2]
./heritability_estimation_GREML_train_set_only.sh PI-18:0_18:1-
./heritability_estimation_GREML_train_set_only.sh Cer-d18:1-20:0-
./heritability_estimation_GREML_train_set_only.sh GM3-d18:1-20:0-
./heritability_estimation_GREML_train_set_only.sh TG-50:2-_[NL-16:1]
./heritability_estimation_GREML_train_set_only.sh PC-16:0_16:0-
./heritability_estimation_GREML_train_set_only.sh PE-P-18:0-18:2-
./heritability_estimation_GREML_train_set_only.sh PC-O-44:6-_-a-
./heritability_estimation_GREML_train_set_only.sh PS-40:5-
./heritability_estimation_GREML_train_set_only.sh LPC-20:5-_[sn2]
./heritability_estimation_GREML_train_set_only.sh SM-d17:1-16:0-
./heritability_estimation_GREML_train_set_only.sh Cer-d19:1-20:0-
./heritability_estimation_GREML_train_set_only.sh TG-52:5-_[NL-18:3]
./heritability_estimation_GREML_train_set_only.sh DG-16:0_22:6-
./heritability_estimation_GREML_train_set_only.sh PE-P-18:0-20:5-
./heritability_estimation_GREML_train_set_only.sh LPC-16:1-_[sn2]
./heritability_estimation_GREML_train_set_only.sh Hex3Cer-d18:1-18:0-
./heritability_estimation_GREML_train_set_only.sh Cer-d20:1-22:0-
./heritability_estimation_GREML_train_set_only.sh PE-P-18:1-20:5-_-a-
./heritability_estimation_GREML_train_set_only.sh PC-42:10-
./heritability_estimation_GREML_train_set_only.sh PC-36:4-_[+OH]
./heritability_estimation_GREML_train_set_only.sh PC-O-16:0-22:6-
./heritability_estimation_GREML_train_set_only.sh LPI-20:4-_[sn1]
./heritability_estimation_GREML_train_set_only.sh PI-37:6-
./heritability_estimation_GREML_train_set_only.sh CE-20:4-
./heritability_estimation_GREML_train_set_only.sh LPC-15:0-_[sn1]
./heritability_estimation_GREML_train_set_only.sh TG-48:0-_[NL-16:0]
./heritability_estimation_GREML_train_set_only.sh TG-54:2-_[NL-20:1]
./heritability_estimation_GREML_train_set_only.sh PC-32:1-
./heritability_estimation_GREML_train_set_only.sh dhCer-d18:0-22:0-
./heritability_estimation_GREML_train_set_only.sh DG-18:0_18:2-
./heritability_estimation_GREML_train_set_only.sh FA-20:4-
./heritability_estimation_GREML_train_set_only.sh PE-17:0_18:1-
./heritability_estimation_GREML_train_set_only.sh LPC-22:1-_[sn1]
./heritability_estimation_GREML_train_set_only.sh TG-53:2-_[SIM]
./heritability_estimation_GREML_train_set_only.sh TG-51:2-_[NL-17:0]
./heritability_estimation_GREML_train_set_only.sh PE-P-18:1-22:6-_-b-
./heritability_estimation_GREML_train_set_only.sh FA-18:0-
./heritability_estimation_GREML_train_set_only.sh AC-15:0-_-a-
./heritability_estimation_GREML_train_set_only.sh LPC-22:5-_[sn1]_-n6-
./heritability_estimation_GREML_train_set_only.sh CE-18:3-
./heritability_estimation_GREML_train_set_only.sh PI-36:2-
./heritability_estimation_GREML_train_set_only.sh PC-P-16:0-14:0-
./heritability_estimation_GREML_train_set_only.sh TG-50:4-_[NL-14:0]
./heritability_estimation_GREML_train_set_only.sh PC-O-18:0-18:1-
./heritability_estimation_GREML_train_set_only.sh PE-15-MHDA_18:1-
./heritability_estimation_GREML_train_set_only.sh AC-20:4-
./heritability_estimation_GREML_train_set_only.sh TG-O-52:2-_[NL-18:1]
./heritability_estimation_GREML_train_set_only.sh LPC-22:4-_[sn1]
./heritability_estimation_GREML_train_set_only.sh PA-36:1-
./heritability_estimation_GREML_train_set_only.sh PE-18:0_22:4-
./heritability_estimation_GREML_train_set_only.sh PE-18:1_18:2-
./heritability_estimation_GREML_train_set_only.sh PE-36:0-
./heritability_estimation_GREML_train_set_only.sh TG-O-54:4-_[NL-18:2]
./heritability_estimation_GREML_train_set_only.sh PC-18:1_20:3-
./heritability_estimation_GREML_train_set_only.sh AC-20:3--OH
./heritability_estimation_GREML_train_set_only.sh LPC-20:2-_[sn1]
./heritability_estimation_GREML_train_set_only.sh TG-O-54:2-_[NL-17:1]
./heritability_estimation_GREML_train_set_only.sh TG-50:2-_[SIM]
./heritability_estimation_GREML_train_set_only.sh PC-P-16:0-18:1-
./heritability_estimation_GREML_train_set_only.sh PC-38:6-_-a-
./heritability_estimation_GREML_train_set_only.sh dhCer-d18:0-24:1-
./heritability_estimation_GREML_train_set_only.sh PC-P-46:7-
./heritability_estimation_GREML_train_set_only.sh LPE-18:0-_[sn2]
./heritability_estimation_GREML_train_set_only.sh S1P-d18:0-
./heritability_estimation_GREML_train_set_only.sh LPE-P-16:0-
./heritability_estimation_GREML_train_set_only.sh TG-48:1-_[NL-16:1]
./heritability_estimation_GREML_train_set_only.sh PI-16:0_20:3-_-b-
./heritability_estimation_GREML_train_set_only.sh TG-52:1-_[SIM]
./heritability_estimation_GREML_train_set_only.sh FA-16:1-
./heritability_estimation_GREML_train_set_only.sh CE-22:4-
./heritability_estimation_GREML_train_set_only.sh PC-33:0-_-a-
./heritability_estimation_GREML_train_set_only.sh GM3-d18:1-18:0-
./heritability_estimation_GREML_train_set_only.sh PE-P-17:0-20:4-_-a-
./heritability_estimation_GREML_train_set_only.sh PI-38:5-_-a-
./heritability_estimation_GREML_train_set_only.sh Cer-d17:1-24:1-
./heritability_estimation_GREML_train_set_only.sh PC-P-17:0-20:4-_-b-
./heritability_estimation_GREML_train_set_only.sh TG-52:5-_[NL-20:4]
./heritability_estimation_GREML_train_set_only.sh DG-18:0_18:1-
./heritability_estimation_GREML_train_set_only.sh LPC-15-MHDA-_[sn1]_-_LPC-17:0-_[sn2]
./heritability_estimation_GREML_train_set_only.sh PC-42:6-_-a-
./heritability_estimation_GREML_train_set_only.sh PC-42:6-_-b-
./heritability_estimation_GREML_train_set_only.sh FA-22:5-
./heritability_estimation_GREML_train_set_only.sh GM3-d18:1-16:0-
./heritability_estimation_GREML_train_set_only.sh Cer-d18:2-24:0-
./heritability_estimation_GREML_train_set_only.sh LPC-P-16:0-
./heritability_estimation_GREML_train_set_only.sh TG-48:2-_[NL-14:0]
./heritability_estimation_GREML_train_set_only.sh LPC-20:0-_[sn1]
./heritability_estimation_GREML_train_set_only.sh DE-16:0-
./heritability_estimation_GREML_train_set_only.sh dimethyl-CE-18:2-
./heritability_estimation_GREML_train_set_only.sh LPC-18:0-_[sn2]
./heritability_estimation_GREML_train_set_only.sh LPE-18:0-_[sn1]
./heritability_estimation_GREML_train_set_only.sh CE-18:1-
./heritability_estimation_GREML_train_set_only.sh PE-P-18:1-18:1-_-a-
./heritability_estimation_GREML_train_set_only.sh PE-P-17:0-22:6-_-b-
./heritability_estimation_GREML_train_set_only.sh PE-P-17:0-22:6-_-a-
./heritability_estimation_GREML_train_set_only.sh LPC-18:2-_[sn1]
./heritability_estimation_GREML_train_set_only.sh LPC-P-18:0-
./heritability_estimation_GREML_train_set_only.sh AC-14:1-
./heritability_estimation_GREML_train_set_only.sh DG-18:0_20:4-
./heritability_estimation_GREML_train_set_only.sh PC-18:0_22:5-_-n3--PC-20:1_20:4-
./heritability_estimation_GREML_train_set_only.sh AC-18:3-
./heritability_estimation_GREML_train_set_only.sh PC-18:0_18:1-
./heritability_estimation_GREML_train_set_only.sh LPC-22:0-_[sn1]
./heritability_estimation_GREML_train_set_only.sh PE-15-MHDA_18:2-
./heritability_estimation_GREML_train_set_only.sh TG-O-52:2-_[SIM]
./heritability_estimation_GREML_train_set_only.sh LPC-17:1-_[sn1]_-b-
./heritability_estimation_GREML_train_set_only.sh SM-d18:1-24:0-
./heritability_estimation_GREML_train_set_only.sh TG-50:4-_[SIM]
./heritability_estimation_GREML_train_set_only.sh PC-16:1_20:4-
./heritability_estimation_GREML_train_set_only.sh FA-14:0-
./heritability_estimation_GREML_train_set_only.sh Hex2Cer-d18:1-20:0-
./heritability_estimation_GREML_train_set_only.sh TG-50:1-_[SIM]
./heritability_estimation_GREML_train_set_only.sh HexCer-d18:2-20:0-
./heritability_estimation_GREML_train_set_only.sh PC-31:1-
./heritability_estimation_GREML_train_set_only.sh LPC-22:6-_[sn2]
./heritability_estimation_GREML_train_set_only.sh AC-26:1-
./heritability_estimation_GREML_train_set_only.sh LPE-18:1-_[sn2]
./heritability_estimation_GREML_train_set_only.sh TG-54:6-_[NL-20:5]
./heritability_estimation_GREML_train_set_only.sh PI-16:0-16:0-
./heritability_estimation_GREML_train_set_only.sh SM-d19:1-24:1-
./heritability_estimation_GREML_train_set_only.sh TG-54:0-_[NL-18:0]
./heritability_estimation_GREML_train_set_only.sh TG-50:3-_[NL-14:1]
./heritability_estimation_GREML_train_set_only.sh FA-16:0-
./heritability_estimation_GREML_train_set_only.sh TG-54:4-_[SIM]
./heritability_estimation_GREML_train_set_only.sh DE-18:2-
./heritability_estimation_GREML_train_set_only.sh PI-18:0_20:3-_-a-
./heritability_estimation_GREML_train_set_only.sh DG-16:0_20:4-
./heritability_estimation_GREML_train_set_only.sh CE-22:6-
./heritability_estimation_GREML_train_set_only.sh PC-16:0_20:5-
./heritability_estimation_GREML_train_set_only.sh Hex3Cer-d18:1-20:0-
./heritability_estimation_GREML_train_set_only.sh TG-O-50:1-_[SIM]
./heritability_estimation_GREML_train_set_only.sh LPC-P-20:0-
./heritability_estimation_GREML_train_set_only.sh LPC-14:0-_[sn1]
./heritability_estimation_GREML_train_set_only.sh PE-P-18:0-18:1-
./heritability_estimation_GREML_train_set_only.sh LPC-P-17:0-_-a-
./heritability_estimation_GREML_train_set_only.sh PE-18:0_20:4-
./heritability_estimation_GREML_train_set_only.sh GD1-d18:1-24:1-
./heritability_estimation_GREML_train_set_only.sh SM-d18:1-16:0-
./heritability_estimation_GREML_train_set_only.sh Hex3Cer-d18:1-22:0-
./heritability_estimation_GREML_train_set_only.sh PI-16:0_20:3-_-a-
./heritability_estimation_GREML_train_set_only.sh SM-38:3-_-a-
./heritability_estimation_GREML_train_set_only.sh AC-18:1--OH
./heritability_estimation_GREML_train_set_only.sh Cer-d16:1-24:1-
./heritability_estimation_GREML_train_set_only.sh CA
./heritability_estimation_GREML_train_set_only.sh PE-18:0_22:6-
./heritability_estimation_GREML_train_set_only.sh CE-24:6-
./heritability_estimation_GREML_train_set_only.sh LPC-22:1-_[sn2]
./heritability_estimation_GREML_train_set_only.sh Cer-d19:1-23:0-
./heritability_estimation_GREML_train_set_only.sh TG-O-50:1-_[NL-18:1]
./heritability_estimation_GREML_train_set_only.sh PE-P-20:0-22:6-
./heritability_estimation_GREML_train_set_only.sh dhCer-d18:0-24:0-
./heritability_estimation_GREML_train_set_only.sh SM-d18:2-16:0-
./heritability_estimation_GREML_train_set_only.sh SM-d18:0-22:0-
./heritability_estimation_GREML_train_set_only.sh TG-52:3-_[NL-18:2]
./heritability_estimation_GREML_train_set_only.sh Hex3Cer-d18:1-24:0-
./heritability_estimation_GREML_train_set_only.sh LPI-18:2-_[sn2]
./heritability_estimation_GREML_train_set_only.sh Cer-d18:2-24:1-
./heritability_estimation_GREML_train_set_only.sh dhCer-d18:0-18:0-
./heritability_estimation_GREML_train_set_only.sh PC-42:7-
./heritability_estimation_GREML_train_set_only.sh PC-42:4-_-b-
./heritability_estimation_GREML_train_set_only.sh AC-18:0-
./heritability_estimation_GREML_train_set_only.sh AC-15:0-_-b-
./heritability_estimation_GREML_train_set_only.sh LPC-19:0-_-a-_[sn1]_[104_sn1]
./heritability_estimation_GREML_train_set_only.sh PC-P-35:2-_-a-
./heritability_estimation_GREML_train_set_only.sh PC-P-18:1-18:1-
./heritability_estimation_GREML_train_set_only.sh Cer-d16:1-24:0-
./heritability_estimation_GREML_train_set_only.sh Cer-d18:2-22:0-
./heritability_estimation_GREML_train_set_only.sh HexCer-d18:1-16:0-
./heritability_estimation_GREML_train_set_only.sh PE-16:0_20:4-
./heritability_estimation_GREML_train_set_only.sh TG-O-54:4-_[NL-17:1]
./heritability_estimation_GREML_train_set_only.sh Cer-d18:1-26:0-
./heritability_estimation_GREML_train_set_only.sh PS-36:2-
./heritability_estimation_GREML_train_set_only.sh TG-54:6-_[SIM]
./heritability_estimation_GREML_train_set_only.sh PC-P-16:0-22:6-
./heritability_estimation_GREML_train_set_only.sh PC-O-42:7-
./heritability_estimation_GREML_train_set_only.sh Cer-d16:1-20:0-
./heritability_estimation_GREML_train_set_only.sh TG-56:6-_[SIM]
./heritability_estimation_GREML_train_set_only.sh Cer-d18:2-23:0-
./heritability_estimation_GREML_train_set_only.sh TG-48:2-_[NL-16:1]
./heritability_estimation_GREML_train_set_only.sh LPC-18:3-_[sn1]_-b-
./heritability_estimation_GREML_train_set_only.sh DG-18:1_20:3-
./heritability_estimation_GREML_train_set_only.sh TG-50:0-_[SIM]
./heritability_estimation_GREML_train_set_only.sh Cer-m18:0-24:1-
./heritability_estimation_GREML_train_set_only.sh SHexCer-d18:1-16:0-OH--
./heritability_estimation_GREML_train_set_only.sh LPE-20:4-_[sn1]
./heritability_estimation_GREML_train_set_only.sh PC-16:1_18:2-
./heritability_estimation_GREML_train_set_only.sh PE-P-18:1-20:3-_-a-
./heritability_estimation_GREML_train_set_only.sh PE-O-18:1-18:2-
./heritability_estimation_GREML_train_set_only.sh LPI-20:4-_[sn2]
./heritability_estimation_GREML_train_set_only.sh HexCer-d18:1-18:0-
./heritability_estimation_GREML_train_set_only.sh PI-16:0_16:1-
./heritability_estimation_GREML_train_set_only.sh PE-18:0_18:2-
./heritability_estimation_GREML_train_set_only.sh LPC-22:5-_-n3-_[sn1]_[104_sn1]
./heritability_estimation_GREML_train_set_only.sh LPC-18:1-_[sn1]
./heritability_estimation_GREML_train_set_only.sh PC-42:8-_-c-
./heritability_estimation_GREML_train_set_only.sh AC-20:3-_-a-
./heritability_estimation_GREML_train_set_only.sh PE-P-18:0-22:6-
./heritability_estimation_GREML_train_set_only.sh AC-17:0-_-b-
./heritability_estimation_GREML_train_set_only.sh AC-16:0-
./heritability_estimation_GREML_train_set_only.sh PG-36:2-
./heritability_estimation_GREML_train_set_only.sh PC-17:0_20:4-
./heritability_estimation_GREML_train_set_only.sh TG-54:1-_[NL-18:1]
./heritability_estimation_GREML_train_set_only.sh Cer-d18:1-16:0-
./heritability_estimation_GREML_train_set_only.sh TG-54:6-_[NL-22:6]
./heritability_estimation_GREML_train_set_only.sh methyl-CE-22:6-
./heritability_estimation_GREML_train_set_only.sh PC-31:0-_-a-
./heritability_estimation_GREML_train_set_only.sh PC-14:0_20:4-
./heritability_estimation_GREML_train_set_only.sh TG-52:1-_[NL-18:1]
./heritability_estimation_GREML_train_set_only.sh Cer-d16:1-16:0-
./heritability_estimation_GREML_train_set_only.sh Cer-d18:1-21:0-
./heritability_estimation_GREML_train_set_only.sh LPC-19:0-_[sn1]_-b-
./heritability_estimation_GREML_train_set_only.sh PC-O-42:5-_-a-
./heritability_estimation_GREML_train_set_only.sh TG-56:9-_[SIM]
./heritability_estimation_GREML_train_set_only.sh PC-18:0_22:6-
./heritability_estimation_GREML_train_set_only.sh Cer-d17:1-24:0-
./heritability_estimation_GREML_train_set_only.sh PC-P-18:0-20:4-
./heritability_estimation_GREML_train_set_only.sh Cer1P-d18:1-16:0-
./heritability_estimation_GREML_train_set_only.sh PE-O-18:1-22:6-
./heritability_estimation_GREML_train_set_only.sh LPC-18:3-_[sn1]_-a--LPC-18:3-_[sn2]_-b-
./heritability_estimation_GREML_train_set_only.sh SM-d18:1-17:0--SM-d17:1-18:0-
./heritability_estimation_GREML_train_set_only.sh PC-O-46:8-
./heritability_estimation_GREML_train_set_only.sh CE-22:0-
./heritability_estimation_GREML_train_set_only.sh LPC-O-24:2-
./heritability_estimation_GREML_train_set_only.sh AC-10:0-
./heritability_estimation_GREML_train_set_only.sh PI-34:1-
./heritability_estimation_GREML_train_set_only.sh TG-O-52:0-_[NL-16:0]
./heritability_estimation_GREML_train_set_only.sh PC-17:1_18:2-
./heritability_estimation_GREML_train_set_only.sh FA-18:2-
./heritability_estimation_GREML_train_set_only.sh PC-P-18:0-22:6-
./heritability_estimation_GREML_train_set_only.sh PC-42:8-_-a-
./heritability_estimation_GREML_train_set_only.sh LPC-20:3-_[sn2]
./heritability_estimation_GREML_train_set_only.sh LPC-20:5-_[sn1]
./heritability_estimation_GREML_train_set_only.sh HexCer-d18:1-24:0-
./heritability_estimation_GREML_train_set_only.sh GM3-d18:1-22:0-
./heritability_estimation_GREML_train_set_only.sh CE-20:4-_[+OH]
./heritability_estimation_GREML_train_set_only.sh PC-P-16:0-18:2-
./heritability_estimation_GREML_train_set_only.sh PC-O-42:4-_-a-
./heritability_estimation_GREML_train_set_only.sh PE-18:1_22:6-_-b-
./heritability_estimation_GREML_train_set_only.sh TG-50:4-_[NL-20:4]
./heritability_estimation_GREML_train_set_only.sh TG-O-52:2-_[NL-17:1]
./heritability_estimation_GREML_train_set_only.sh PC-15-MHDA_18:1-
./heritability_estimation_GREML_train_set_only.sh PI-15-MHDA_18:2--PI-17:0_18:2-
./heritability_estimation_GREML_train_set_only.sh Cer-d19:1-22:0-
./heritability_estimation_GREML_train_set_only.sh Cer-d17:1-23:0-
./heritability_estimation_GREML_train_set_only.sh LPE-22:6-_[sn1]
./heritability_estimation_GREML_train_set_only.sh PC-38:2-
./heritability_estimation_GREML_train_set_only.sh Cer-d16:1-23:0-
./heritability_estimation_GREML_train_set_only.sh TG-O-50:1-_[NL-16:0]
./heritability_estimation_GREML_train_set_only.sh TG-50:1-_[NL-14:0]
./heritability_estimation_GREML_train_set_only.sh CE-24:1-
./heritability_estimation_GREML_train_set_only.sh PS-38:3-
./heritability_estimation_GREML_train_set_only.sh TG-52:5-_[SIM]
./heritability_estimation_GREML_train_set_only.sh DG-18:1_20:5-
./heritability_estimation_GREML_train_set_only.sh PC-42:9-_-a-
./heritability_estimation_GREML_train_set_only.sh TG-51:0-_[NL-16:0]
./heritability_estimation_GREML_train_set_only.sh TG-50:3-_[NL-16:1]
./heritability_estimation_GREML_train_set_only.sh AC-26:0-
./heritability_estimation_GREML_train_set_only.sh PE-O-16:0-22:6-
./heritability_estimation_GREML_train_set_only.sh PI-18:0_22:5-_-n6-
./heritability_estimation_GREML_train_set_only.sh HexCer-d18:2-24:0-
./heritability_estimation_GREML_train_set_only.sh PE-O-38:5-_-a-
./heritability_estimation_GREML_train_set_only.sh PE-P-16:0-22:5-_-n6-
./heritability_estimation_GREML_train_set_only.sh PC-16:0_20:3-_-b-
./heritability_estimation_GREML_train_set_only.sh TG-O-54:3-_[NL-18:1]
./heritability_estimation_GREML_train_set_only.sh PC-15-MHDA_18:2-
./heritability_estimation_GREML_train_set_only.sh HexCer-d18:1-22:0-
./heritability_estimation_GREML_train_set_only.sh PI-18:0_20:2-
./heritability_estimation_GREML_train_set_only.sh CE-22:5-
./heritability_estimation_GREML_train_set_only.sh TG-49:1-_[SIM]
./heritability_estimation_GREML_train_set_only.sh TG-50:0-_[NL-18:0]
./heritability_estimation_GREML_train_set_only.sh TG-54:7-_[SIM]
./heritability_estimation_GREML_train_set_only.sh PC-P-35:2-_-b-
./heritability_estimation_GREML_train_set_only.sh PE-O-36:5-
./heritability_estimation_GREML_train_set_only.sh PC-35:5-
./heritability_estimation_GREML_train_set_only.sh SM-37:1-
./heritability_estimation_GREML_train_set_only.sh PC-O-18:0-22:6-
./heritability_estimation_GREML_train_set_only.sh PE-17:0_22:6-
./heritability_estimation_GREML_train_set_only.sh PA-36:4-
./heritability_estimation_GREML_train_set_only.sh PG-36:1-
./heritability_estimation_GREML_train_set_only.sh LPC-O-24:0-
./heritability_estimation_GREML_train_set_only.sh PE-15-MHDA_20:4-
./heritability_estimation_GREML_train_set_only.sh HexCer-d16:1-22:0-
./heritability_estimation_GREML_train_set_only.sh PC-P-16:0-16:1-
./heritability_estimation_GREML_train_set_only.sh PC-16:0_18:3-_-b-
./heritability_estimation_GREML_train_set_only.sh Hex2Cer-d18:2-18:0-
./heritability_estimation_GREML_train_set_only.sh TG-52:3-_[SIM]
./heritability_estimation_GREML_train_set_only.sh Cer-d18:2-16:0-
./heritability_estimation_GREML_train_set_only.sh LPC-20:3-_[sn1]
./heritability_estimation_GREML_train_set_only.sh PE-P-18:1-22:5-_-b-
./heritability_estimation_GREML_train_set_only.sh PE-18:0_20:3-_-a-
./heritability_estimation_GREML_train_set_only.sh TG-52:1-_[NL-18:0]
./heritability_estimation_GREML_train_set_only.sh AC-12:1-
./heritability_estimation_GREML_train_set_only.sh HexCer-d16:1-24:0-
./heritability_estimation_GREML_train_set_only.sh DG-O-18:1-18:1-_[NL-O-18:1]
./heritability_estimation_GREML_train_set_only.sh LPI-18:2-_[sn1]
./heritability_estimation_GREML_train_set_only.sh PC-O-34:4-
./heritability_estimation_GREML_train_set_only.sh PC-P-15:0-20:4-_-a-
./heritability_estimation_GREML_train_set_only.sh SM-d18:2-24:0-
./heritability_estimation_GREML_train_set_only.sh TG-52:2-_[NL-16:0]
./heritability_estimation_GREML_train_set_only.sh LPC-O-22:1-
./heritability_estimation_GREML_train_set_only.sh DG-18:2_20:4-
./heritability_estimation_GREML_train_set_only.sh SM-d17:1-14:0-
./heritability_estimation_GREML_train_set_only.sh CE-18:0-
./heritability_estimation_GREML_train_set_only.sh PE-O-16:0-20:3-
./heritability_estimation_GREML_train_set_only.sh AC-16:1-
./heritability_estimation_GREML_train_set_only.sh Cer-m18:0-23:0-
./heritability_estimation_GREML_train_set_only.sh DE-20:5-
./heritability_estimation_GREML_train_set_only.sh LPE-18:1-_[sn1]
./heritability_estimation_GREML_train_set_only.sh SM-44:2-
./heritability_estimation_GREML_train_set_only.sh PE-16:0_22:6-
./heritability_estimation_GREML_train_set_only.sh LPE-18:2-_[sn2]
./heritability_estimation_GREML_train_set_only.sh LPC-19:1-_-b-
./heritability_estimation_GREML_train_set_only.sh PE-P-18:0-20:3-_-b-
./heritability_estimation_GREML_train_set_only.sh TG-48:2-_[NL-18:2]
./heritability_estimation_GREML_train_set_only.sh SM-d18:2-18:1-
./heritability_estimation_GREML_train_set_only.sh PC-33:1-
./heritability_estimation_GREML_train_set_only.sh PC-42:3-_-a-
./heritability_estimation_GREML_train_set_only.sh LPC-22:5-_[sn2]_-n3-
./heritability_estimation_GREML_train_set_only.sh PC-P-36:3-
./heritability_estimation_GREML_train_set_only.sh PC-15-MHDA_20:4-
./heritability_estimation_GREML_train_set_only.sh PI-18:1_18:2-
./heritability_estimation_GREML_train_set_only.sh LPC-O-16:0-
./heritability_estimation_GREML_train_set_only.sh PC-42:5-_-b-
./heritability_estimation_GREML_train_set_only.sh Cer-d18:2-26:0-
./heritability_estimation_GREML_train_set_only.sh DG-18:2_18:2-
./heritability_estimation_GREML_train_set_only.sh TG-52:4-_[NL-18:2]
./heritability_estimation_GREML_train_set_only.sh TG-54:3-_[NL-18:2]
./heritability_estimation_GREML_train_set_only.sh FA-22:4-
./heritability_estimation_GREML_train_set_only.sh FA-22:6-
./heritability_estimation_GREML_train_set_only.sh PE-O-38:5-_-b-
./heritability_estimation_GREML_train_set_only.sh PE-18:0_18:1-
./heritability_estimation_GREML_train_set_only.sh CE-14:0-
./heritability_estimation_GREML_train_set_only.sh TG-48:2-_[NL-14:1]
./heritability_estimation_GREML_train_set_only.sh DG-18:1_18:1-
./heritability_estimation_GREML_train_set_only.sh PC-14:0_22:6-
./heritability_estimation_GREML_train_set_only.sh TG-56:6-_[NL-20:4]
./heritability_estimation_GREML_train_set_only.sh TG-56:8-_[NL-20:4]
./heritability_estimation_GREML_train_set_only.sh TG-56:7-_[NL-22:6]
./heritability_estimation_GREML_train_set_only.sh TG-52:3-_[NL-16:1]
./heritability_estimation_GREML_train_set_only.sh TG-O-50:2-_[NL-18:1]
./heritability_estimation_GREML_train_set_only.sh PC-16:1_22:6-
./heritability_estimation_GREML_train_set_only.sh SM-37:2-
./heritability_estimation_GREML_train_set_only.sh TG-O-52:1-_[NL-16:0]
./heritability_estimation_GREML_train_set_only.sh LPC-19:1-_-c-
./heritability_estimation_GREML_train_set_only.sh Cer-d18:1-24:1-
./heritability_estimation_GREML_train_set_only.sh PE-P-15:0-20:4-_-b-
./heritability_estimation_GREML_train_set_only.sh TG-52:5-_[NL-20:5]
./heritability_estimation_GREML_train_set_only.sh LPC-16:0-_[sn1]
./heritability_estimation_GREML_train_set_only.sh PE-P-18:1-22:4-
./heritability_estimation_GREML_train_set_only.sh LPC-O-18:0-
./heritability_estimation_GREML_train_set_only.sh Cer-d20:1-24:0-
./heritability_estimation_GREML_train_set_only.sh LPC-19:0-_[sn2]_-a-
./heritability_estimation_GREML_train_set_only.sh LPC-18:1-_[sn2]
./heritability_estimation_GREML_train_set_only.sh methyl-DE-18:2-
./heritability_estimation_GREML_train_set_only.sh CE-16:0-
./heritability_estimation_GREML_train_set_only.sh TG-56:8-_[NL-20:5]
./heritability_estimation_GREML_train_set_only.sh Ubiquinone
./heritability_estimation_GREML_train_set_only.sh TG-50:2-_[NL-18:2]
./heritability_estimation_GREML_train_set_only.sh HexCer-d18:1-24:1-
./heritability_estimation_GREML_train_set_only.sh PE-18:0_20:3-_-b-
./heritability_estimation_GREML_train_set_only.sh TG-O-50:3-_[NL-18:2]
./heritability_estimation_GREML_train_set_only.sh LPC-O-24:1-
./heritability_estimation_GREML_train_set_only.sh PC-18:1_22:6-_-a-
./heritability_estimation_GREML_train_set_only.sh TG-O-50:2-_[NL-16:1]
./heritability_estimation_GREML_train_set_only.sh FA-20:3-
./heritability_estimation_GREML_train_set_only.sh LPC-19:0-_[sn1]_-a-_-_LPC-19:0-_[sn2]_-b-
./heritability_estimation_GREML_train_set_only.sh TG-48:3-_[NL-18:3]
./heritability_estimation_GREML_train_set_only.sh SM-d16:1-23:0--SM-d17:1-22:0-
./heritability_estimation_GREML_train_set_only.sh PC-P-15:0-20:4-_-b-
./heritability_estimation_GREML_train_set_only.sh PE-16:0_18:1-
./heritability_estimation_GREML_train_set_only.sh PE-20:0_20:4-
./heritability_estimation_GREML_train_set_only.sh TG-51:0-_[SIM]
./heritability_estimation_GREML_train_set_only.sh PI-18:0_22:5-_-n3-
./heritability_estimation_GREML_train_set_only.sh PC-33:0-_-b-
./heritability_estimation_GREML_train_set_only.sh TG-54:2-_[NL-18:0]
./heritability_estimation_GREML_train_set_only.sh PE-P-16:0-22:6-
./heritability_estimation_GREML_train_set_only.sh PE-16:0_16:1-
./heritability_estimation_GREML_train_set_only.sh PC-O-18:1-18:1-
./heritability_estimation_GREML_train_set_only.sh TG-52:4-_[NL-18:3]
./heritability_estimation_GREML_train_set_only.sh PE-O-16:0-20:4-
./heritability_estimation_GREML_train_set_only.sh PE-P-20:0-20:4-
./heritability_estimation_GREML_train_set_only.sh SM-d18:0-16:0-
./heritability_estimation_GREML_train_set_only.sh SM-40:4-
./heritability_estimation_GREML_train_set_only.sh PI-18:0_20:4-
./heritability_estimation_GREML_train_set_only.sh DE-22:6-
./heritability_estimation_GREML_train_set_only.sh PC-44:12-
./heritability_estimation_GREML_train_set_only.sh PE-P-15:0-22:6-_-b-
./heritability_estimation_GREML_train_set_only.sh TG-O-50:2-_[SIM]
./heritability_estimation_GREML_train_set_only.sh AC-22:6-
./heritability_estimation_GREML_train_set_only.sh PC-38:6-_[+OH]
./heritability_estimation_GREML_train_set_only.sh Sph-d18:2-
./heritability_estimation_GREML_train_set_only.sh PC-O-46:7-_-b-
./heritability_estimation_GREML_train_set_only.sh PC-P-46:8-
./heritability_estimation_GREML_train_set_only.sh DG-18:2_22:6-
./heritability_estimation_GREML_train_set_only.sh PC-17:0_18:1-
./heritability_estimation_GREML_train_set_only.sh TG-54:5-_[NL-20:4]
./heritability_estimation_GREML_train_set_only.sh TG-O-52:1-_[NL-18:1]
./heritability_estimation_GREML_train_set_only.sh TG-56:8-_[SIM]
./heritability_estimation_GREML_train_set_only.sh PC-15:0_20:4-
./heritability_estimation_GREML_train_set_only.sh DG-O-18:0-20:0-_[NL-O-18:0]
./heritability_estimation_GREML_train_set_only.sh PC-O-16:0-20:4-
./heritability_estimation_GREML_train_set_only.sh methyl-CE-20:4-
./heritability_estimation_GREML_train_set_only.sh SM-d18:1-24:1-
./heritability_estimation_GREML_train_set_only.sh Cer-d19:1-24:0-
./heritability_estimation_GREML_train_set_only.sh PI-15-MHDA_18:1--PI-17:0_18:1-
./heritability_estimation_GREML_train_set_only.sh TG-56:7-_[SIM]
./heritability_estimation_GREML_train_set_only.sh PC-18:2_18:2-
./heritability_estimation_GREML_train_set_only.sh PC-34:5-
./heritability_estimation_GREML_train_set_only.sh PC-17:0_22:6-
./heritability_estimation_GREML_train_set_only.sh CE-17:0-
./heritability_estimation_GREML_train_set_only.sh Hex2Cer-d18:1-24:1-
./heritability_estimation_GREML_train_set_only.sh TG-56:7-_[NL-20:5]
./heritability_estimation_GREML_train_set_only.sh PI-38:6-
./heritability_estimation_GREML_train_set_only.sh LPC-18:3-_[sn2]_-a-
./heritability_estimation_GREML_train_set_only.sh SM-d18:2-20:0-
./heritability_estimation_GREML_train_set_only.sh PC-O-42:5-_-b-
./heritability_estimation_GREML_train_set_only.sh PC-32:2-
./heritability_estimation_GREML_train_set_only.sh AC-24:0-
./heritability_estimation_GREML_train_set_only.sh SM-35:2-_-b-
./heritability_estimation_GREML_train_set_only.sh PC-36:6-_-a-
./heritability_estimation_GREML_train_set_only.sh PS-40:6-
./heritability_estimation_GREML_train_set_only.sh PE-P-16:0-20:5-
./heritability_estimation_GREML_train_set_only.sh Hex2Cer-d18:1-22:0-
./heritability_estimation_GREML_train_set_only.sh TG-50:4-_[NL-18:3]
./heritability_estimation_GREML_train_set_only.sh LPC-16:0-_[sn2]
./heritability_estimation_GREML_train_set_only.sh TG-56:6-_[NL-22:5]
./heritability_estimation_GREML_train_set_only.sh TG-49:1-_[NL-17:1]
./heritability_estimation_GREML_train_set_only.sh PC-P-16:0-18:3-
./heritability_estimation_GREML_train_set_only.sh PE-P-19:0-20:4-_-a-
./heritability_estimation_GREML_train_set_only.sh TG-O-52:1-_[SIM]
./heritability_estimation_GREML_train_set_only.sh TG-54:5-_[NL-18:3]
./heritability_estimation_GREML_train_set_only.sh PC-O-42:6-
./heritability_estimation_GREML_train_set_only.sh CE-18:2-
./heritability_estimation_GREML_train_set_only.sh S1P-d18:1-
./heritability_estimation_GREML_train_set_only.sh PI-18:0_20:3-_-b-
./heritability_estimation_GREML_train_set_only.sh PE-P-15:0-20:4-_-a-
./heritability_estimation_GREML_train_set_only.sh TG-O-54:3-_[NL-17:1]
./heritability_estimation_GREML_train_set_only.sh PC-38:5-_-a-
./heritability_estimation_GREML_train_set_only.sh PS-36:1-
./heritability_estimation_GREML_train_set_only.sh SM-d18:1-20:0--SM-d16:1-22:0-
./heritability_estimation_GREML_train_set_only.sh PC-44:4-_-b-
./heritability_estimation_GREML_train_set_only.sh AC-12:0-
./heritability_estimation_GREML_train_set_only.sh Hex3Cer-d18:1-24:1-
./heritability_estimation_GREML_train_set_only.sh Hex2Cer-d18:2-24:1-
./heritability_estimation_GREML_train_set_only.sh TG-O-50:2-_[NL-18:2]
./heritability_estimation_GREML_train_set_only.sh PC-39:5-_-a-
./heritability_estimation_GREML_train_set_only.sh PC-17:0_18:2-
./heritability_estimation_GREML_train_set_only.sh LPC-20:2-_[sn2]
./heritability_estimation_GREML_train_set_only.sh dxCA
./heritability_estimation_GREML_train_set_only.sh PE-P-16:0-20:4-
./heritability_estimation_GREML_train_set_only.sh TG-52:4-_[NL-16:1]
./heritability_estimation_GREML_train_set_only.sh FA-17:1-
./heritability_estimation_GREML_train_set_only.sh PE-P-20:0-18:2-
./heritability_estimation_GREML_train_set_only.sh AC-16:0--OH
./heritability_estimation_GREML_train_set_only.sh SHexCer-d18:1-24:0-
./heritability_estimation_GREML_train_set_only.sh PC-28:0-
./heritability_estimation_GREML_train_set_only.sh TG-53:2-_[NL-18:1]
./heritability_estimation_GREML_train_set_only.sh Hex2Cer-d16:1-16:0-
./heritability_estimation_GREML_train_set_only.sh PC-42:2-_-b-
./heritability_estimation_GREML_train_set_only.sh Cer-d17:1-18:0-
./heritability_estimation_GREML_train_set_only.sh LPE-18:2-_[sn1]
./heritability_estimation_GREML_train_set_only.sh CE-16:2-
./heritability_estimation_GREML_train_set_only.sh PC-P-42:5-
./heritability_estimation_GREML_train_set_only.sh dimethyl-CE-18:1-
./heritability_estimation_GREML_train_set_only.sh SM-44:1-
./heritability_estimation_GREML_train_set_only.sh Cer-d17:1-22:0-
./heritability_estimation_GREML_train_set_only.sh TG-58:8-_[NL-22:6]
./heritability_estimation_GREML_train_set_only.sh Cer-m18:0-22:0-
./heritability_estimation_GREML_train_set_only.sh TG-48:3-_[SIM]
./heritability_estimation_GREML_train_set_only.sh methyl-DE-18:1-
./heritability_estimation_GREML_train_set_only.sh TG-49:1-_[NL-16:1]
./heritability_estimation_GREML_train_set_only.sh LPC-14:0-_[sn2]
./heritability_estimation_GREML_train_set_only.sh PC-15-MHDA_22:6-
./heritability_estimation_GREML_train_set_only.sh PC-O-34:1-
./heritability_estimation_GREML_train_set_only.sh PI-39:6-
./heritability_estimation_GREML_train_set_only.sh TG-48:2-_[SIM]
./heritability_estimation_GREML_train_set_only.sh DE-18:1-
./heritability_estimation_GREML_train_set_only.sh LPC-17:1-_[sn2]_-a-
./heritability_estimation_GREML_train_set_only.sh PE-P-18:1-18:2-_-b-
./heritability_estimation_GREML_train_set_only.sh PE-P-18:0-20:4-
./heritability_estimation_GREML_train_set_only.sh TG-O-54:2-_[NL-18:1]
./heritability_estimation_GREML_train_set_only.sh PC-O-18:1-18:2-
./heritability_estimation_GREML_train_set_only.sh DG-16:1_18:1-
./heritability_estimation_GREML_train_set_only.sh Cer-m18:1-20:0-
./heritability_estimation_GREML_train_set_only.sh TG-58:10-_[NL-22:6]
./heritability_estimation_GREML_train_set_only.sh LPC-17:1-_-a-_[sn1]_[104_sn1]
./heritability_estimation_GREML_train_set_only.sh PC-O-35:4-
./heritability_estimation_GREML_train_set_only.sh LPC-15-MHDA-_[sn2]
./heritability_estimation_GREML_train_set_only.sh Sph-d18:1-
./heritability_estimation_GREML_train_set_only.sh PE-P-18:1-18:1-_-b-
./heritability_estimation_GREML_train_set_only.sh PE-P-16:0-18:1-
./heritability_estimation_GREML_train_set_only.sh AC-22:5--OH
./heritability_estimation_GREML_train_set_only.sh deDE-18:2-
./heritability_estimation_GREML_train_set_only.sh DG-16:0_16:1-
./heritability_estimation_GREML_train_set_only.sh S1P-d18:2-
./heritability_estimation_GREML_train_set_only.sh TG-52:2-_[SIM]
./heritability_estimation_GREML_train_set_only.sh PE-16:1_18:2-
./heritability_estimation_GREML_train_set_only.sh LPC-18:2-_[+OH]
./heritability_estimation_GREML_train_set_only.sh TG-51:1-_[SIM]
./heritability_estimation_GREML_train_set_only.sh SM-42:4-
./heritability_estimation_GREML_train_set_only.sh LPC-18:0-_[sn1]
./heritability_estimation_GREML_train_set_only.sh PIP1-38:4-
./heritability_estimation_GREML_train_set_only.sh Cer-d17:1-20:0-
./heritability_estimation_GREML_train_set_only.sh TG-50:2-_[NL-18:1]
./heritability_estimation_GREML_train_set_only.sh LPC-22:0-_[sn2]
./heritability_estimation_GREML_train_set_only.sh TG-50:3-_[SIM]
./heritability_estimation_GREML_train_set_only.sh DG-O-18:1-20:0-_[NL-O-18:1]
./heritability_estimation_GREML_train_set_only.sh TG-56:7-_[NL-22:5]
./heritability_estimation_GREML_train_set_only.sh TG-56:7-_[NL-20:4]
./heritability_estimation_GREML_train_set_only.sh TG-50:3-_[NL-18:3]
./heritability_estimation_GREML_train_set_only.sh SM-d16:1-24:1-
./heritability_estimation_GREML_train_set_only.sh PE-P-20:0-18:1-
./heritability_estimation_GREML_train_set_only.sh PE-16:0_18:3-_-b-
./heritability_estimation_GREML_train_set_only.sh AC-17:0-_-a-
./heritability_estimation_GREML_train_set_only.sh LPC-22:6-_[+OH]
./heritability_estimation_GREML_train_set_only.sh TG-O-50:1-_[NL-17:1]
./heritability_estimation_GREML_train_set_only.sh LPC-20:0-_[sn2]
./heritability_estimation_GREML_train_set_only.sh LPC-20:1-_[sn1]
./heritability_estimation_GREML_train_set_only.sh PE-P-18:1-20:3-_-b-
./heritability_estimation_GREML_train_set_only.sh AC-18:2-
./heritability_estimation_GREML_train_set_only.sh GM3-d18:1-24:1-
./heritability_estimation_GREML_train_set_only.sh LPE-16:0-_[sn1]
./heritability_estimation_GREML_train_set_only.sh PE-P-16:0-18:3-
./heritability_estimation_GREML_train_set_only.sh Cer-d17:1-16:0-
./heritability_estimation_GREML_train_set_only.sh PE-P-16:0-22:5-_-n3-
./heritability_estimation_GREML_train_set_only.sh PC-18:1_22:6-_-b-
./heritability_estimation_GREML_train_set_only.sh DG-16:0_18:2-
./heritability_estimation_GREML_train_set_only.sh AC-22:5-
./heritability_estimation_GREML_train_set_only.sh SM-d17:1-24:1-
./heritability_estimation_GREML_train_set_only.sh PE-P-18:1-20:5-_-b-
./heritability_estimation_GREML_train_set_only.sh SM-d16:1-19:0-
./heritability_estimation_GREML_train_set_only.sh Cer-m18:1-24:1-
./heritability_estimation_GREML_train_set_only.sh TG-52:2-_[NL-18:2]
./heritability_estimation_GREML_train_set_only.sh TG-O-52:2-_[NL-16:0]
./heritability_estimation_GREML_train_set_only.sh LPC-O-18:1-
./heritability_estimation_GREML_train_set_only.sh PI-15-MHDA_20:4-\PI-17:0_20:4-
./heritability_estimation_GREML_train_set_only.sh PC-42:8-_-b-
./heritability_estimation_GREML_train_set_only.sh PI_-38:5-_-b-
./heritability_estimation_GREML_train_set_only.sh PC-P-38:5-_-b-
./heritability_estimation_GREML_train_set_only.sh PC-42:4-_-a-
./heritability_estimation_GREML_train_set_only.sh CE-16:1-
./heritability_estimation_GREML_train_set_only.sh TG-54:5-_[SIM]
./heritability_estimation_GREML_train_set_only.sh PA-34:1-
./heritability_estimation_GREML_train_set_only.sh PC-15:0_20:3-
./heritability_estimation_GREML_train_set_only.sh TG-48:1-_[SIM]
./heritability_estimation_GREML_train_set_only.sh PG-34:1-
./heritability_estimation_GREML_train_set_only.sh DG-17:0_18:1-
./heritability_estimation_GREML_train_set_only.sh PE-P-20:1-22:6-
./heritability_estimation_GREML_train_set_only.sh PC-P-44:5-
./heritability_estimation_GREML_train_set_only.sh Cer-d16:1-18:0-
./heritability_estimation_GREML_train_set_only.sh TG-54:1-_[SIM]
./heritability_estimation_GREML_train_set_only.sh PE-P-20:1-20:4-
./heritability_estimation_GREML_train_set_only.sh DE-20:4-
./heritability_estimation_GREML_train_set_only.sh PI-18:0_22:4-
./heritability_estimation_GREML_train_set_only.sh PC-16:0_20:3-_-a-
./heritability_estimation_GREML_train_set_only.sh HexCer-d16:1-18:0-
./heritability_estimation_GREML_train_set_only.sh PE-17:0_20:4-
./heritability_estimation_GREML_train_set_only.sh PE-P-16:0-20:3-_-b-
./heritability_estimation_GREML_train_set_only.sh PE-P-18:1-18:2-_-a-
./heritability_estimation_GREML_train_set_only.sh PE-P-18:0-22:5-_-n3-
./heritability_estimation_GREML_train_set_only.sh LPE-22:6-_[sn2]
./heritability_estimation_GREML_train_set_only.sh PC-P-18:0-22:5-
./heritability_estimation_GREML_train_set_only.sh TG-52:4-_[SIM]
./heritability_estimation_GREML_train_set_only.sh SM-44:3-
./heritability_estimation_GREML_train_set_only.sh CE-22:1-
./heritability_estimation_GREML_train_set_only.sh PC-O-42:4-_-b-
./heritability_estimation_GREML_train_set_only.sh PC-18:1_18:1-
./heritability_estimation_GREML_train_set_only.sh TG-51:2-_[NL-17:1]
./heritability_estimation_GREML_train_set_only.sh PE-16:0_18:3-_-a-
./heritability_estimation_GREML_train_set_only.sh PC-P-38:5-_-a-
./heritability_estimation_GREML_train_set_only.sh PC-O-46:7-_-a-
./heritability_estimation_GREML_train_set_only.sh TG-50:2-_[NL-14:0]
./heritability_estimation_GREML_train_set_only.sh DG-14:0_16:0-
./heritability_estimation_GREML_train_set_only.sh SM-d18:0-14:0-
./heritability_estimation_GREML_train_set_only.sh AC-14:0--OH
./heritability_estimation_GREML_train_set_only.sh PC-16:0_20:4-
